// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Remplacez ces valeurs par celles de votre console Firebase
      // Project Settings > General > Your apps > Web app
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        // Retourne les options web par défaut pour Android si non configuré
        // L'application fonctionnera en mode limité sans configuration Firebase complète
        return web;
      case TargetPlatform.iOS:
        return web;
      case TargetPlatform.macOS:
        return web;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZz-uiJfMjULPNey6BYaH12MNovSETJ9I',
    appId: '1:779368892991:web:9f20cdb10534c31ea0068a',
    messagingSenderId: '779368892991',
    projectId: 'p-data-c',
    authDomain: 'p-data-c.firebaseapp.com',
    storageBucket: 'p-data-c.firebasestorage.app',
    measurementId: 'G-CQJHBV7FNP',
  );
}
